language: node_js

node_js:
  - 10

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install
  - ls -la node_modules

script:
  - yarn lint
  - yarn test
