[[redirects]]
  from = "https://tiptap.scrumpy.io/*"
  to = "https://www.tiptap.dev/:splat"
  status = 301

[[redirects]]
  from = "/docs/*"
  to = "https://tiptap-docs.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

