# A GitHub Action that labels issues/PRs if the creator is a sponsor of the owner
# Documentation: https://github.com/JasonEtco/is-sponsor-label-action

name: add labels

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  build:
    name: is-sponsor-label

    runs-on: ubuntu-latest

    steps:
      - uses: JasonEtco/is-sponsor-label-action@v1
        with:
          label: sponsor 💖
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
